--- name:exoter
# the device port
serial_port: /dev/exoter-dgps  #ttyS4 for PC104, if connected through USB/Serial converter then use ttyUSB1; in HDPR repo: ttyXR0
# Baud rate to open the serial com_port.
serial_baudrate: 38400
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.2
# from frame for the transformer
#gnss_source_frame: "body" #transformer names. No transformation convention
# to frame for the transformer
#gnss_target_frame: "world_osg" #transformer names. No transformation convention

--- name:HDPR
# the device port
serial_port: /dev/hdpr-dgps
# Baud rate to open the serial com_port.
serial_baudrate: 115200
#serial_baudrate: 9600
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.2

--- name:EvaluationBoard
# the device port
serial_port: /dev/ttyUSB1
# Baud rate to open the serial com_port.
serial_baudrate: 38400
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.1

--- name:Netherlands
# This UTM zone is also valid for Toulouse (CNES)
# UTM zone for conversion of WGS84 to UTM
utm_zone: 31
# UTM north for conversion of WGS84 to UTM
utm_north: true
# Geodetic datum typically NAD83 or WGS84 
geodetic_datum: WGS84

# from frame for the transformer
gnss_source_frame: "body" #transformer names. No transformation convention
# to frame for the transformer
gnss_target_frame: "world_osg" #transformer names. No transformation convention

--- name:Spain
# UTM zone for conversion of WGS84 to UTM
utm_zone: 30
# UTM north for conversion of WGS84 to UTM
utm_north: true
# Geodetic datum typically NAD83 or WGS84 
geodetic_datum: WGS84

# from frame for the transformer
gnss_source_frame: "body" #transformer names. No transformation convention
# to frame for the transformer
gnss_target_frame: "world_osg" #transformer names. No transformation convention

--- name:ESTEC
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 597220.14273647161
  - 5786238.5623347349
  - 2.9529999999999998

--- name:SEROM
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 377771.4
  - 4823945.2
  - 143.674

--- name:DECOS
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  #- 597481.68
  #- 5785983.94
  #- 5.87
  # exoter values:
  - 597400.9       # (597467.8-81.9)+14
  - 5785944.4      # (5785972.5-55.1)+24
    #- 597197.5       # (597467.8-81.9)
    #- 5786210.4      # (5785972.5-55.1)
  - 1.95
  
--- name:DECOS_AUTONOMY
# Origin in UTM coordinates where the whole DECOS area is well into positive coordinates.
pose_origin:
  data:
  - 597469.22 
  - 5785971.45 
  - 5.87

--- name:TENERIFE_AUTONOMY
# Origin in UTM coordinates where the whole DECOS area is well into positive coordinates.
pose_origin:
  data:
  - 597642.22
  - 5786059.45
  - 2296.00

--- name:Tenerife
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 344043.0
  - 3127403.0
  - 2296.0

--- name:Tenerife_Teleop
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 344182.92
  - 3127638.37
  - 2299.0

--- name:Malaga
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 367028
  - 4064510
  - 52.138

--- name:calibration
# Offset to 0 so the value in rock-display would show the value needed to set here
pose_origin:
  data:
  - 0.0
  - 0.0
  - 0.0
