--- name:default

--- name:exoter
#
locomotion_modes: [DRIVING, WHEEL_WALKING]
slope_values: [0,5,10,15,20]
#
#          Locomotion1        Locomotion2
#Obstacles slope1-slope2-...  slope1-slope2-... value much higher than for terrains (f.e. 100 times)
#Terrain1  slope1-slope2-...  slope1-slope2-... 
#Terrain2  slope1-slope2-...  slope1-slope2-...
#
cost_data: [1000,1000,1000,1000,1000, 1000,1000,1000,1000,1000,
            14.3,16.3,18.3,20.3,22.3, 20.0,20.0,20.0,20.0,20.0,
            25.0,25.0,25.0,25.0,25.0, 20.0,20.0,20.0,20.0,20.0]

local_res: 0.05

risk_distance: 0.7

reconnect_distance: 0.5

risk_ratio: 10.0



--- name:exoter_umaRescueArea
#
locomotion_modes: [DRIVING]
slope_values: [0,5,10,15,20,25,30,35,40,45]
#
#          Locomotion1        Locomotion2
#Obstacles slope1-slope2-...  slope1-slope2-... value much higher than for terrains (f.e. 100 times)
#Terrain1  slope1-slope2-...  slope1-slope2-... 
#Terrain2  slope1-slope2-...  slope1-slope2-...
#
cost_data: [10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,
            10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0]

local_res: 0.03

global_res: 0.03

risk_distance: 0.7

reconnect_distance: 0.5

risk_ratio: 1.0

elevationFile: '../../../rover/data/maps/umaRescueArea/umaRA_elevationMap.txt'
localCostFile: ''
globalCostFile: '../../../rover/data/maps/umaRescueArea/umaRA_globalTerrainMap.txt'


--- name:hdpr
#
locomotion_modes: [DRIVING]
slope_values: [0,5,10,15]
#
#          Locomotion1        Locomotion2
#Obstacles slope1-slope2-...  slope1-slope2-... value much higher than for terrains (f.e. 100 times)
#Terrain1  slope1-slope2-...  slope1-slope2-... 
#Terrain2  slope1-slope2-...  slope1-slope2-...
#
cost_data: [120.0,    120.0,    120.0,  120.0,
            10.0,     15,       25,     40.0,
            10.0,     15,       25,     40.0,
			32.0,     37,       47,     62.0]

#global_res: 1.0

local_res: 0.1

risk_distance: 1.5

reconnect_distance: 0.0

risk_ratio: 1.1

--- name:slip&obstacles

num_criteria: 2

weights: [50,50] #%

--- name:slip

num_criteria: 1

weights: [100] #%

--- name:decos

elevationFile: '../../../rover/data/maps/decos/elevationMap.txt'
localCostFile: '../../../rover/data/maps/decos/local_terrainMap.txt'
globalCostFile: '../../../rover/data/maps/decos/global_terrainMap.txt'
global_offset: [0,0]
global_res: 1.0
#local_res: 0.0625


--- name:decos_3terrains

elevationFile: '../../../rover/data/maps/decos/elevationMap.txt'
localCostFile: '../../../rover/data/maps/decos/local_terrainMap.txt'
globalCostFile: '../../../rover/data/maps/decos/global_terrainMap_3terrains.txt'
global_offset: [0,0]
global_res: 1.0
#local_res: 0.0625


--- name:prl

elevationFile: '../../../rover/data/maps/prl/elevationMap.txt'
localCostFile: '../../../rover/data/maps/prl/local_terrainMap.txt'
globalCostFile: '../../../rover/data/maps/prl/global_terrainMap.txt'
global_offset: [0,0]
global_res: 1.0
#local_res: 0.05

--- name:prl_2cm

elevationFile: '../../../rover/data/maps/prl/DEM_PRL_2cm.txt'
localCostFile: '../../../rover/data/maps/prl/local_terrainMap.txt'
globalCostFile: '../../../rover/data/maps/prl/global_terrainMap_2cm.txt'
global_offset: [0,0]
global_res: 0.02
#local_res: 0.05


--- name:marsTerrain_2cm
elevationFile: '../../../rover/data/maps/marsTerrain/marsTerrain_2cm.txt'
localCostFile: '../../../rover/data/maps/marsTerrain/global_marsTerrain_2cm.txt'
globalCostFile: '../../../rover/data/maps/marsTerrain/global_marsTerrain_2cm.txt'
global_offset: [500,500]
global_res: 0.02
#local_res: 0.05

--- name:exoter_rover
locomotion_modes: [DRIVING]
slope_values: [0,5,10,15,20,25,30,35,40,45]
#
#          Locomotion1        Locomotion2
#Obstacles slope1-slope2-...  slope1-slope2-... value much higher than for terrains (f.e. 100 times)
#Terrain1  slope1-slope2-...  slope1-slope2-... 
#Terrain2  slope1-slope2-...  slope1-slope2-...
#
cost_data: [10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,
            10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0]

local_res: 0.10

global_res: 0.10

risk_distance: 0.7

reconnect_distance: 0.5

risk_ratio: 1.0

elevationFile: '../../../rover/data/maps/umaRescueArea_2021/elevation_map_UMA.txt'
localCostFile: '../../../rover/data/maps/umaRescueArea_2021/global_obsmap_UMA.txt'
globalCostFile: '../../../rover/data/maps/umaRescueArea_2021/global_obsmap_UMA.txt'
global_offset: [0,0]
